### ISSUE TITLE
HTTPS server

### ISSUE THREAD

**Issue by bartekn** [stellar/federation#3]
Let's discuss whether to add the ability to start `https` server.

Pros/cons:
- Since we require `https` for all federation servers it will allow organizations to run it without dealing with nxginx or other proxies.
- Nobody really cares if `/federation` endpoint is in the root domain. In other words, orgs can start federation server at federation123.example.com subdomain and it will be discoverable using `stellar.toml` file.
- Most organizations (even smaller ones) use load balancers and it's pretty trivial to forward a specific path to a http server and serve it via https.

**Comment by jedmccaleb** [comment]
Yeah I think we should add it. it is pretty simple right?

**Comment by nullstyle** [comment]
Yeah, real simple:  https://golang.org/pkg/net/http/#ListenAndServeTLS
