### ISSUE TITLE
Unable to change username to user_login in database [queries] config without failure

### ISSUE THREAD

**Issue by sacarlson** [stellar/federation#4]
I have federation working perfectly when I use the default values for [queries] 
with test data in the mysql database this works.
[queries]
federation = "SELECT username, account_id FROM wp_users WHERE username = ?"
reverse-federation = "SELECT username, account_id FROM wp_users WHERE account_id = ?"

however when I change username to user_login even when the colum in the database does exist and have the same data in it 
I get error: Server error: missing destination name user_login

with this [queries]  config
[queries]
federation = "SELECT user_login, account_id FROM wp_users WHERE user_login = ?"
reverse-federation = "SELECT user_login, account_id FROM wp_users WHERE account_id = ?"

my temp work around is to temp create an added colum in our database that matches username with the same data as user_login.  I took a short look at the code at the point of failure but my C go programing is weak today.

I've attached the mysql.sql that I used to isolate and duplicate this problem
[federation_test.sql.zip](https://github.com/stellar/federation/files/88540/federation_test.sql.zip)

**Comment by bartekn** [comment]
You can't change result fields. You need to alias them to make it working:

```
[queries]
federation = "SELECT account_id as id FROM wp_users WHERE user_login = ?"
reverse-federation = "SELECT user_login as name FROM wp_users WHERE account_id = ?"
```

From the README file:

> federation - Implementation dependent query to fetch federation results, should return either 1 or 3 columns. These columns should be labeled `id` , `memo`, `memo_type`. Memo and memo_type are optional - check Federation docs)
> reverse-federation - Implementation dependent query to fetch reverse federation results, should return one column. This column should be labeled `name`.

Also, make sure you're using the latest version. Fields names have changed.

**Comment by sacarlson** [comment]
Yes this modified [queries] you provided when I run with 0.0.3 version works perfect now. thanks again and I should have noted the older version commit I was using for my results were from around version 0.0.1.  so I also see this as closed.
